---
development:
  adapter: postgresql
  username: postgres
  database: padrino-development
  host: localhost

test:
  adapter: postgresql
  username: postgres
  database: padrino-test
  host: localhost
